source 'https://rubygems.org'

gem 'rails', '3.2.13'
gem 'jquery-rails'
gem 'devise'
gem 'helper_methods', '~>0.0.16'
gem 'simple_form'
gem 'responders'

gem 'slim-rails'

# gem 'jbuilder'
# gem 'cocoon'
# gem 'kaminari'
# gem 'RedCloth'
# gem 'impressionist'
# gem 'friendly_id'
# gem 'omniauth'
# gem 'omniauth-facebook'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

group :development do
  gem 'sqlite3'
  gem 'thin'
  gem 'letter_opener'
end

group :development, :test do
  gem 'rspec-rails'
  gem 'shoulda-matchers'
  gem 'faker'
end

group :test do
  gem 'factory_girl_rails', '~> 4.0'
  gem 'simplecov', require: false
end

group :production do
  gem 'mysql2'
end

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'